# Generated by Django 6.1 on 2026-09-02 12:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=10)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AlertDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dismissed_for_due_date', models.DateField()),
                ('dismissed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_dismissed', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_dismissal', to='billing.invoice')),
            ],
            options={
                'db_table': 'alert_dismissals',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=255)),
                ('plan_name', models.CharField(max_length=100)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborators_added', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='billing.subscription')),
            ],
            options={
                'db_table': 'collaborators',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='billing.invoice')),
            ],
            options={
                'db_table': 'credit_notes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['invoice'], name='idx_cn_invoice')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cn_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('voided', 'Voided'), ('field_changed', 'Field changed'), ('credit_note_issued', 'Credit note issued'), ('note_added', 'Note added')], max_length=32)),
                ('old_status', models.CharField(blank=True, max_length=10, null=True)),
                ('new_status', models.CharField(blank=True, max_length=10, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_events', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='billing.invoice')),
            ],
            options={
                'db_table': 'invoice_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='idx_evt_invoice_time'), models.Index(condition=models.Q(('event_type', 'status_changed')), fields=['new_status', 'created_at'], name='idx_evt_status_time')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['owner'], name='idx_sub_owner'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan_name'], name='idx_sub_plan'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(condition=models.Q(('archived_at__isnull', True)), fields=['archived_at'], name='idx_sub_active'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='sub_price_positive'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription'], name='idx_inv_sub'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='idx_inv_status_due'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='idx_inv_due'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('paid_at__isnull', False)), fields=['paid_at'], name='idx_inv_paid_at'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(condition=models.Q(('issued_at__isnull', False)), fields=['issued_at'], name='idx_inv_issued_at'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='inv_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lte', models.F('period_end'))), name='inv_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), ('void_reason__isnull', False)), models.Q(models.Q(('status', 'void'), _negated=True), ('void_reason__isnull', True)), _connector='OR'), name='inv_void_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'void'), _negated=True), fields=('subscription', 'period_start', 'period_end'), name='uq_invoice_period'),
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['subscription', 'user'], name='idx_collab_sub_user'),
        ),
        migrations.AddIndex(
            model_name='collaborator',
            index=models.Index(fields=['user'], name='idx_collab_user'),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('subscription', 'user'), name='uq_collaborator'),
        ),
    ]
